// vuejs-project/src/components/layouts/Layout.vue
<script setup>

</script>

<template>
    <header>
        <h1 class="text-medium text-gradient">Unalive</h1>
    </header>
    <main>
        <slot />
    </main>
    <footer>
        <small>Created by</small>
        <a href="/" target="_blank">
            <img src="https://media.licdn.com/dms/image/v2/C5603AQG6Q4W3kWANtw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1630988413596?e=1749686400&v=beta&t=MBMG5v7M1LKk_26tHHa30BC8F1CiLgsnsm6rf05rOSs" alt="pfp"/>
            <p>@Jamezmcarthur</p>
            <i class="fa-brands fa-linkedin-in"></i>
        </a>
    </footer>
</template>

<style scoped></style>

// reactjs-project/src/components/layouts/Layout.jsx
export default function Layout(props) {
    const { children } = props

    const header = (
        <header>
            <h1 className="text-medium text-gradient">
                Unalive
            </h1>
        </header>
    )

    const footer = (
        <footer>
            <small>Created by</small>
            <a target="_blank" href="https://www.linkedin.com/in/jamezmcarthur/">
                <img alt="pfp" src="https://media.licdn.com/dms/image/v2/C5603AQG6Q4W3kWANtw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1630988413596?e=1747872000&v=beta&t=07eM4oD3FQOgoGqbRiV15zqzeZSmCZkUVW3cXctLNic" />
                <p>@jamezmcarthur</p>
                <i className="fa-brands fa-linkedin-in"></i>
            </a>
        </footer>
    )

    return (
        <>
            {header}
            < main >
                {children}
            </main >
            {footer}
        </>
    )
}
