// svelte-project/src/App.svelte
<script>
  import Calendar from "./lib/Calendar.svelte";
  import Clocks from "./lib/Clocks.svelte";
  import Hero from "./lib/Hero.svelte";
  import Layout from "./lib/layouts/Layout.svelte";
  import Summary from "./lib/Summary.svelte";
</script>

<Layout>
  {#snippet headache({
    data,
    birthDate,
    name,
    percentage,
    lifeExpectancy,
    handleToggleModal,
    resetData,
  })}
    <Hero {resetData} {name} {percentage} {data} {handleToggleModal} />
    <Clocks {data} />
    <Calendar {data} {lifeExpectancy} />
    <Summary {birthDate} {lifeExpectancy} />
  {/snippet}
</Layout>

// reactjs-project/src/App.jsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import Layout from './components/layouts/Layout'
import Hero from './components/Hero'
import Clocks from './components/Clocks'
import Calendar from './components/Calendar'
import Summary from './components/Summary'


function App() {
  

  return (
    <Layout>
      <Hero />
      <Clocks />
      <Calendar />
      <Summary />
    </Layout>
    
  )
}

export default App
