// vuejs-project/src/components/Calendar.vue
<script setup>
    import { computed } from 'vue'
    const { data, lifeExpectancy } = defineProps({
        data: Object,
        lifeExpectancy: Object
    })

    const yearsArr = computed(() => [...Array(lifeExpectancy.value).keys()])
    const weeksArr = [...Array(52).keys()]
    const weekNum = computed(() => lifeExpectancy.value * 52 - parseInt(data.value['weeks']))
    const finalWeek = computed(() => lifeExpectancy.value * 52)

    function getWeeksArr(wksArr, yrIndex) {
        return wksArr.map((val, valIndex) => {
            const currWeek = yrIndex * 52 + valIndex
            const dotStyle = currWeek == finalWeek.value - 1 
                ? ' death' 
                : currWeek < weekNum.value 
                ? ' solid'
                : currWeek == weekNum.value 
                ? ' pulse' 
                : '' 
            return {week: val, currWeek, dotStyle}
        })
    }
</script>

<template>
    <section id="calendar">
        <p><i>Each square of dots represents 52 weeks / 1 year of your life.</i></p>
        <div class="dozen-grid">
            <div class="year-grid" v-for="(year, yearIndex) in yearsArr" :key="yearIndex">
                <div 
                v-for="(week, weekIndex) in getWeeksArr(weeksArr, yearIndex)"
                :key="weekIndex"
                class="dot"
                :class="week.dotStyle"  
                ></div>
            </div>
        </div>
    </section>
</template>

<style scoped></style>

// reactjs-project/src/components/Calendar.jsx
function DozenDisplay(props) {
    const { weeksArr, yearIndex, weekNum, finalWeek } = props
    return (
        <div className="year-grid">
            {weeksArr.map((week, weekIndex) => {
                const currWeek = yearIndex * 52 + weekIndex
                const dotStyle = currWeek == finalWeek - 1 ?
                    ' death' :
                    currWeek < weekNum ?
                        ' solid' :
                        currWeek == weekNum ?
                            ' pulse' : ''

                return (
                    <div className={'dot  ' + dotStyle} key={weekIndex} />
                )
            })}
        </div>
    )
}

export default function Calendar(props) {
    const { lifeExpectancy, data } = props
    const yearsArr = [...Array(lifeExpectancy).keys()]
    const weeksArr = [...Array(52).keys()]

    const weekNum = lifeExpectancy * 52 - parseInt(data['weeks'])
    const finalWeek = lifeExpectancy * 52

    return (
        <section>
            <p><i>Each square of dots represents 52 weeks / 1 year of your life.</i></p>
            <div className="dozen-grid">
                {yearsArr.map((year, yearIndex) => {
                    return (
                        <DozenDisplay key={yearIndex} weeksArr={weeksArr} weekNum={weekNum} finalWeek={finalWeek} yearIndex={yearIndex} />
                    )
                })}
            </div>
        </section>
    )
}
